### ISSUE TITLE
Share card image is off

### ISSUE THREAD

**Issue by fredhohman** [gtvis/gtvis.github.io#1]
The share card image on Twitter is off. Should be adjusted to be the correct size, likely putting the full logo on a white background where the white background has the correct size.

![image](https://user-images.githubusercontent.com/5741691/121050782-ba8b8300-c76d-11eb-9701-dda007dac71d.png)

You can see it shows this way for many social sites as well.

https://www.opengraph.xyz/url/https:%2F%2Fvis.gatech.edu%2F/

**Comment by arpitnarechania** [comment]
Fixed by [8f57be0](https://github.com/gtvis/gtvis.github.io/commit/8f57be075192c14ed03988b06652eb5b61affb2c) and [617610d](https://github.com/gtvis/gtvis.github.io/commit/617610d94d20012cc7e61174c02aee3e8f5eca6b).

<img width="1267" alt="Screenshot 2021-06-12 at 2 02 55 PM" src="https://user-images.githubusercontent.com/2376894/121785627-ccfc2700-cb88-11eb-9e87-197ad6e9ec0c.png">
